services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_mem
    ports:
      - "45533:5432"